run:
  timeout: 5m
  skip-dirs:
  - pkg/client
  - pkg/apis
linters:
  enable:
  - deadcode
  - typecheck
  - structcheck
  - varcheck
  - megacheck
  - gofmt
  - unconvert
  - nakedret
  - misspell
  - golint
  - bodyclose
  - govet
  - gosec
  - gosimple
  - goimports
  - staticcheck
  - ineffassign
  - errcheck
  - dogsled
  - depguard
  - lll
  - unparam
  - rowserrcheck
  - sqlclosecheck
  - gomnd
  - exportloopref
  - goconst
  - godot
  - maligned
  - noctx
  - stylecheck
  - nolintlint
  - prealloc
  - whitespace
  - gofumpt
  - asciicheck
  - gci
issues:
